#Travis - 2/16/18
language: ruby
rvm:
  - 2.1
cache: bundler
install: gem install rb-inotify -v 0.9.10 && gem install ruby_dep -v 1.3.1 && gem install listen -v 3.0.8 && gem install jekyll-watch -v 2.0.0 && gem install jekyll -v 3.7.3 && gem install jekyll-redirect-from -v 0.13.0 && gem install jekyll-paginate-v2 -v 1.9.4 && gem install s3_website && gem install bundler -v 1.17.2 && gem install rake -v 10.5.0 && gem install public_suffix -v 2.0.5 && gem install addressable -v 2.5.1 && gem install ffi -v 1.9.18
script: jekyll build
after_success: 
  - s3_website push
notifications:
    slack: aiacc:DQJx1jxSipYMHzXBVtf4kMGH
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false
