#Travis - 2/16/18
language: ruby
rvm:
  - 2.1
#cache: bundler
install: gem install s3_website && bundle install
script: bundle exec jekyll build
after_success: 
  - s3_website push
notifications:
    slack: aiacc:DQJx1jxSipYMHzXBVtf4kMGH
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false
