---
title: AIA Winter Retreat
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    retreat_date: 2017-10-17 00:00:00.000000000 Z
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    retreat_date: TBA
    retreat_location: TBA
    retreat_ID: 0
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Celebrating the Induction to the Hall of Faith
url: 
baseurl: 
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
